config/routes.rb
SoundMelonV2Radio::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", passwords: "users/passwords", sessions: "users/sessions" }

  devise_scope :user do
    match '/signout', :to => 'devise/sessions#destroy', :as => :destroy_user_session

    #User routes
    match '/user/:id', to: 'users#show'
    match '/user_checkin', to: 'users#checkin'
    match '/email_signup', to: 'users#email_signup'
    match '/accept_terms', to: 'users#accept_terms'
    match '/init_fb_meta', to: 'users#init_fb_meta'
    match '/search_cities', to: 'users#search_cities'
    match '/add_city', to: 'users#add_city'
    match '/reload_fb_meta', to: 'users#reload_fb_meta'
    match '/update_user_meta', to: 'users#update_user_meta'
    match '/update_fb_meta', to: 'users#update_fb_meta'
    match '/add_favorite', to: 'users#add_favorite'
    match '/show_favorites', to: 'users#show_favorites'
    match '/update_favorites', to: 'users#update_favorites'
    match '/user_account', to: 'users#edit_account'
    match '/update_account', to: 'users#update_account'
    match '/add_media_account', to: 'users#add_media_account'
    match '/user_invites', to: 'users#new_invites'
    match '/user_remove', to: 'users#destroy'
  end

	resources :songs
  
  root to: 'welcome#index'

  match '/about', to: redirect('http://about.soundmelon.com')

#Admin routes
#	post 'send_mass_email' => 'users#send_mass_email'

#Report routes
	match '/report_song', to: 'reports#report_song'
	match '/send_report', to: 'reports#send_report'

#Feedback routes
	match '/feedback_form', to: 'feedbacks#new'
	match '/feedback_send', to: 'feedbacks#create'

#Artist routes
	match '/sc_request', to: 'artists#sc_request'
	match '/sc_oauth_callback', to: 'artists#sc_oauth_callback'
	match '/yt_request', to: 'artists#yt_request'
	match '/yt_oauth_callback', to: 'artists#yt_oauth_callback'
	match '/artist_show', to: 'artists#show'
	match '/artist_profile_update', to: 'artists#profile_update'
	match '/request_unlink', to: 'artists#request_unlink'
	match '/unlink_media_account', to: 'artists#unlink_media_account'
	match '/artist_profile_edit', to: 'artists#profile_edit'
	match '/artist_info', to: 'artists#show_artist_info'

#Song routes
	match '/make_public', to: 'songs#make_public'
	match '/request_playlist', to: 'songs#request_playlist'
  match '/request_history_reset', to: 'songs#history_reset'
	match '/get_source_tags', to: 'songs#get_source_tags'
	match '/new_song', to: 'songs#new'
	match '/edit_song', to: 'songs#edit'

	
#Invite routes
	match '/send_invite' => 'invites#create'
	match "/:invite_token", to: redirect('/')

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :artist_name, :youtube_token, :soundcloud_token, :artist_photo,
									:website, :city, :genre_tags, :facebook_link, :twitter_link, :itunes_link
	
	before_save :record_city
	
	has_attached_file :artist_photo,
		storage: :dropbox,
		dropbox_credentials: Rails.root.join("config/dropbox.yml"),
		styles: {medium: "300x300", thumb: "100x100"},
		dropbox_options: {
      path: proc { |style| "#{style}/#{id}_#{artist_photo.original_filename}" }
    },
		default_url: "/assets/artist-default.jpg"
	belongs_to :user
	has_many :song, dependent: :destroy
	has_many :reports, as: :reportable #Allow Song to be reported
	serialize :youtube_token
	serialize :soundcloud_token
	serialize :genre_tags
	
	private
		def record_city
			self.city = self.user.city
			self.city_coords = self.user.city_coords
		end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	include ApplicationHelper
	helper_method :yt_auth_ids, :sc_auth_ids, :new_yt_client
	require 'soundcloud'
	respond_to :js, :json, :html, :xml

	def create
		@name = current_user.first_name + (current_user.last_name.nil? || current_user.last_name == '' ? '' : ' ' + current_user.last_name)
		@artist = Artist.new(artist_name: @name)
		@artist.user = current_user
		if @artist.save
			current_user.update_column(:is_artist, true)
			current_user.update_column(:artist_id, @artist.id)
		end
	end

	def show
	end

	def yt_request
		ids = yt_auth_ids
		yt_authorize_url = 'https://accounts.google.com/o/oauth2/auth?client_id=' + ids[:client_id] + '&redirect_uri=' + ids[:redirect_uri] + '&scope=' + ids[:yt_scope] + '&response_type=code&approval_prompt=force&access_type=offline'
		redirect_to yt_authorize_url
	end

	def yt_oauth_callback
		conn = yt_oauth_setup
		ids = yt_auth_ids
		@result = obtain_yt_token(conn, params[:code], ids)
		@new_tokens = Hash.transform_keys_to_symbols(JSON.load(@result.body)) 
		if !@new_tokens.has_key?(:error)
			@new_tokens[:expires_at] = Time.parse(@result.env[:response_headers][:date]).to_i + @new_tokens[:expires_in] 
			if !current_user.is_artist?
				create
			end
			current_artist.update_attributes(youtube_token: @new_tokens)
		end
		flash[:music_account_callback] = true
		redirect_to root_path
	end

	def sc_request
		client = Soundcloud.new(sc_auth_ids)
		redirect_to client.authorize_url
	end

	def sc_oauth_callback
		@client = Soundcloud.new(sc_auth_ids)
		if !params.has_key?('error')
			@client.exchange_token(code: params[:code])
			@new_tokens = @client.options.except(:on_exchange_token)
			if !current_user.is_artist?
				create
			end
			current_artist.update_attributes(soundcloud_token: @new_tokens)
		end
		flash[:music_account_callback] = true
		redirect_to root_path
	end

	def profile_edit
	end

	def profile_update
		@artist = Artist.find_by_id(params[:artist][:id])
		params[:artist][:genre_tags] = !params[:artist][:genre_tags].nil? ? params[:artist][:genre_tags].split(',') : @artist.genre_tags
		if @artist.update_attributes(params[:artist])
			@artist.update_column(:profile_edited, true)
			if(params[:artist][:artist_photo])
				write_flash('notification', 'Your Profile has been updated')
			end
			
		end
	end
	
	def request_unlink
		@artist = Artist.find(params[:artist][:id])
		@source = params[:artist][:source]
	end

	def unlink_media_account
		@still_artist = true
		@artist = Artist.find_by_id(params[:artist][:id])
		@account = params[:artist][:account]
		@acct_songs = Song.where(artist_id: @artist.id, upload_source: @account)
		@acct_songs.each do |song|
			Song.find_by_id(song.id).destroy
		end
		if @account == 'youtube'
			@artist.youtube_token = nil
		elsif @account == 'soundcloud'
			@artist.soundcloud_token = nil
		end
		if @artist.save
			write_flash('notification', "Your #{@account} account has been unlinked")
		end
	end
	
	def show_artist_info
		@artist_id = Song.find_by_song_id(params[:song_id]).artist_id
	end

end

app/helpers/artists_helper.rb
require 'rubygems'
require 'faraday'	

module ArtistsHelper

end

app/views/artists/_available_uploads.html.haml
- if all_songs.size > 0
	- all_songs.each do |song|
		- song = song[1]
		- if song.class == YouTubeIt::Model::Video
			- song_id = song.unique_id
			- song_url = song.player_url
			- song_private = song.perm_private
			- duration = song.duration
			- upload_source = 'youtube'
			- source_abbr = 'YT'
			- @current_song = Song.where(artist_id: current_artist.id, song_id: song_id)
			- img_src = song.thumbnails.first.url
			- no_brand = false
			- source_tags = song.keywords
		- if song.class == Hashie::Mash
			- song_id = song.id
			- song_url = song.permalink_url
			- song_private = (song.sharing == 'private')
			- duration = song.duration/1000.0
			- upload_source = 'soundcloud'
			- source_abbr = 'SC'
			- @current_song = Song.where(artist_id: current_artist.id, song_id: song_id)
			- sc_logo = "/assets/sc-placeholder.png"
			- img_src = (song.artwork_url.nil?) ? sc_logo : song.artwork_url
			- no_brand = (song.artwork_url.nil?) ? true : false
			- source_tags = ( song.genre.nil? ? [] : song.genre.split() ) | ( song.tag_list.nil? ? [] : song.tag_list.split(' ') )
			- source_tags.delete_if {|tag| tag.include? "soundcloud:source"}
		- is_blocked = BlockedUpload.exists?(song_id: song_id)
		- too_short = duration < 30
		- too_long = duration > 1500
		- bad_duration = too_short || too_long
		

		- #if duration < 121
		- #elsif duration > 1500
		- #else
		- @in_db = !@current_song.empty?
		- @is_active = (@in_db && @current_song.first.active)
		- @edit_action = @in_db ? "edit" : "new"
		- state = @is_active && !song_private ? "active" : "inactive"
		- if song_private && @is_active
			- @current_song.first.active = false
			- @is_active = false
			- @current_song.first.save

		.song-wrapper{id: song_id}
			
			.song-content
			
				.song-basic
					.song-image{style: "background: url(#{img_src}) center/ #{no_brand ? 'contain' : 'cover'} no-repeat"}
						- if !no_brand
							.brand-logo{class: 'source-' + source_abbr.downcase}
					.song-information
						%span.song-title= song.title
						%span.duration= to_minutes(duration)
						%span.state{class: state}= state
					- if is_blocked
						.block-msg 
							%span This song has been blocked due to reporting and investigation.
					- if bad_duration
						.block-msg 
							%span This song is too #{too_short ? 'short' : 'long'}!
				- if !is_blocked && !bad_duration && !Song.exists?(song_id: song_id)
					= link_to new_song_path({song_id: song_id, upload_source: upload_source, song_url: song_url, song_private: song_private, source_tags: source_tags, song_title: song.title, song_image: img_src, duration: duration}), remote: true, class: 'song-link new' do
						%span.div-link
				- elsif !is_blocked && !bad_duration
					- id = Song.find_by_song_id(song_id).id
					= link_to edit_song_path({id: id, song_id: song_id, upload_source: upload_source, song_url: song_url, song_private: song_private, source_tags: source_tags, song_title: song.title, song_image: img_src, duration: duration}), remote: true, class: 'song-link edit' do
						%span.div-link
						
			.section-divider

app/views/artists/_music_admin_footer.html.haml
.footer-content

	- @artist = current_artist

	.setting-section
		- if !@artist.youtube_token.nil?
			%span connected to 
			.yt-link 
				= link_to("youtube", request_unlink_path(artist: {source: 'youtube', id: current_artist.id}), remote: true, class: 'request-unlink', id: 'youtube-unlink')

		- else
			%span add 
			.yt-link= link_to("youtube", yt_request_path)
			
	.divider
			
			
	.setting-section
		- if !@artist.soundcloud_token.nil?
			%span connected to 
			.sc-link
				= link_to("soundcloud", request_unlink_path(artist: {source: 'soundcloud', id: current_artist.id}), remote: true, class: 'request-unlink', id: 'soundcloud-unlink')

		- else
			%span add 
			.sc-link= link_to("soundcloud", sc_request_path)
			
:javascript

app/views/artists/_profile_form.html.haml
#artist-profile-form
	- @artist = current_artist
	.name.form-block.single-input.section-wrapper
		= form_for(@artist, remote: true, url: artist_profile_update_path) do |f|
			.label Artist Name
			= f.text_field :artist_name, class: 'text-box'
			= f.hidden_field :id, value: @artist.id
			.clear
	
	.section-wrapper
		.section-divider

	.photo.form-block.section-wrapper
		= form_for(@artist, remote: true, url: artist_profile_update_path) do |f|
			= f.hidden_field :id, value: @artist.id
			.label Your Artist Photo
			.clear
			.sub-label This is how people will see you when they click on your artist name in the player.
			
			.photo-edit
				.content
				
					.upload-wrapper
						.preview{style: "background: url(#{@artist.artist_photo.url(:thumb)}) center no-repeat; background-size: cover;"}
						= f.file_field :artist_photo, class: 'file-select overlay'

					.action-buttons

						.submit-wrapper
							.underlay
								%span browse
							= f.file_field :artist_photo, class: 'overlay'

						.submit-wrapper.disabled
							.underlay
								%span upload image
							= f.submit "upload image", class: 'overlay'
	.section-wrapper
		.section-divider
			
	.website.form-block.single-input.section-wrapper

		= form_for(@artist, remote: true, url: artist_profile_update_path) do |f|
			- @genre_tags = @artist.genre_tags.nil? ? [] : @artist.genre_tags
			= f.hidden_field :id, value: @artist.id

			.input-wrapper
				.label Website
				= f.text_field :website, class: 'text-box'
				.clear

			.input-wrapper
				.label Facebook
				= f.text_field :facebook_link, class: 'text-box'
				.clear

			.input-wrapper
				.label Twitter
				= f.text_field :twitter_link, class: 'text-box'
				.clear

			.section-divider.padded-divider

			.input-wrapper
				.sub-label{style:"padding-bottom: 10px;"} Add a link to your iTunes profile so fans can access your catalogue and buy tunes.
				.label iTunes
				= f.text_field :itunes_link, class: 'text-box'
				.clear
			= f.submit "", class: 'hidden'

			.section-divider.padded-divider

	.artist-tags.form-block.section-wrapper
		= form_for(@artist, remote: true, url: artist_profile_update_path) do |f|
			- @genre_tags = @artist.genre_tags.nil? ? [] : @artist.genre_tags
			= f.hidden_field :id, value: @artist.id

			.sub-label Include tags so fans can discover you, eg: "metal", "indie", "toronto", "experimental"
			.tag-form= f.text_area :genre_tags, value: @genre_tags.join(','), id: 'artist-genre-tags'

:javascript
	$(document).ajaxStart(function() {
		$('.modal#artist-profile .spinner').show();
	});

	$(document).ajaxStop(function() {
		$('.modal#artist-profile .spinner').hide();
	});

	$('#artist-profile-form form').find('input[type=text], textarea').blur(function() {
		$(this).closest('form').submit();
	});


	$('#artist-genre-tags').tagsInput({
		'defaultText': 'add more tags...',
		'height': '150px',
		'width': 'auto',
		'onAddTag': function() {
			console.log(this.id);
			$(this).closest('form').submit();
		},
		'onRemoveTag': function() {
			$(this).closest('form').submit();
		}
	});

	$('#artist-profile-form .photo-edit input[type="submit"]').click(function(e) {
		if($(this).closest('.submit-wrapper').hasClass('disabled')) {
			e.preventDefault();
		}
	});
	
	$('#artist-profile-form .photo-edit input[type="file"]').on('change', function() {
		readURL(this);
	});
	
	function readURL(input) {
		if(input.files && input.files[0]) {
			var reader = new FileReader();
			reader.onload = function(e) {
				$('#artist-profile-form .photo-edit .preview').css('background-image', 'url(' + e.target.result + ')');
			}
			
			reader.readAsDataURL(input.files[0]);
			$('#artist-profile-form .photo-edit input[type="submit"]').closest('.submit-wrapper').removeClass('disabled');
		}
	
	}

app/views/artists/_request_unlink_form.html.haml
.unlink-form
	= form_for(@artist, remote: true, url: unlink_media_account_path) do |f|
		= f.hidden_field :id, value: @artist.id
		= f.hidden_field :account, value: @source
		Would you like to unlink your 
		%span{class: @source == 'youtube' ? 'yt-link' : 'sc-link'}= @source.capitalize
		account from Soundmelon?

		.wrapper
			.submit.button{onclick: '$(this).closest("form").submit();'}
				%span yes
				/.submit-wrapper= f.submit "yes", class: 'overlay'
			.cancel.button
				%span no
		
:javascript
	$('.unlink-form .cancel').click(function() {
		$('#artist-media .unlink-form').hide();
	});

app/views/artists/_show_artist_profile.html.haml
.container
	- @artist = Artist.find(artist_id)
	.wrapper
		.profile-picture{style: "background: url(#{@artist.artist_photo(:medium)}) center no-repeat; background-size: cover;"}
		
		.content
			.label= @artist.artist_name
			.sub-label 
				%span.prefix Joined at 
				%span.data= @artist.created_at.strftime("%b %d, %Y")
			- if !@artist.city.nil? && @artist.city.size > 0
				.sub-label
					%span.prefix From 
					%span.data= @artist.city

		.artist-social
			- social_links = {'twitter' => {'link' => @artist.twitter_link, 'tagline' => 'follow us on'}, 'facebook' => {'link' => @artist.facebook_link, 'tagline' => 'like us on'}, 'website' => {'link' => @artist.website, 'tagline' => 'visit our'}}
			- has_social = @artist.website || @artist.facebook_link || @artist.twitter_link
			- has_itunes = @artist.itunes_link
			- if has_social
				.social-items
					.label visit artist at

					- social_links.keys.each do |key|
						- link = social_links[key]['link']
						- if !link.nil? && link.size > 0
							- link = /^http/.match(link) ? link : "http://#{link}"
							.artist-link.artist-social-icon{class: key}
								%a.filled-link{href: link, target: '_blank'}

			- if has_itunes
				.purchase-items
					- if !@artist.itunes_link.nil? && @artist.itunes_link.size > 0
						.itunes-logo
							- link = @artist.itunes_link
							- link = /^http/.match(link) ? link : "http://#{link}"
							- link += '?at=' + ENV['ITUNES_TOKEN']
							%a.filled-link{href: link, target: '_blank'}
			- if !has_social && !has_itunes
				.no-info No additional info

app/views/artists/_unlink_accounts.html.haml
- if !current_artist.youtube_token.nil?
	= link_to("Unlink Youtube", unlink_media_account_path(artist: {account: 'youtube', id: current_artist.id}), remote: true, class: 'hover-link', id: 'youtube-unlink')
- if !current_artist.soundcloud_token.nil?
	= link_to("Unlink Soundcloud", unlink_media_account_path(artist: {account: 'soundcloud', id: current_artist.id}), remote: true, class: 'hover-link', id: 'soundcloud-unlink')

app/views/artists/profile_edit.js.haml
:plain
	console.log('editing Artist profile');
	$('.modal#artist-profile #profile-section .main-content .content').html('#{j( render "artists/profile_form" )}');
	$(".modal#artist-profile").show();

app/views/artists/profile_update.js.haml
:plain
	var messageFlash = #{@messages.to_json};
	if(messageFlash) {
		FlashManager.showMessage(messageFlash);
	}

app/views/artists/request_unlink.js.haml
:plain
	$('#artist-media .main-content > .content').prepend('#{j( render "artists/request_unlink_form" )}');

app/views/artists/show.html.haml
- @artist = current_artist

- @all_songs = []
- if !@artist.youtube_token.nil?
	- yt_ids = yt_auth_ids
	- yt_tokens = @artist.youtube_token
	- @yt_client = new_yt_client(yt_ids, yt_tokens)
	- if yt_tokens[:expires_at] < Time.now.to_i
		- @yt_client = refresh_yt_client(@yt_client)
	- @yt_client.my_videos.videos.each do |video|
		- @all_songs << [Time.parse(video.published_at.to_s), video]

- if !@artist.soundcloud_token.nil?
	- @sc_client = refresh_sc_client(@artist)
	- tracks = @sc_client.get('/me/tracks', order: 'created_at')
	- tracks.each do |track|
		- @all_songs << [Time.parse(track.created_at), track]

- if @all_songs.size > 0
	- @all_songs = @all_songs.sort_by {|pair| pair[0]}
	- @all_songs = @all_songs.reverse
	
.viewport.section-wrapper
	.overview#available-uploads
		= render 'artists/available_uploads', all_songs: @all_songs

:javascript
	//$('.modal#music-admin #scrollbar1').tinyscrollbar();
	$(document).ready(function() {
		$('.modal#music-admin .reload-content, .div-link').click(function() {
			$('#music-admin .spinner').show();
		});
		
		$('.modal#music-admin .content .song-content').click(function() {
			console.log($(this).find('.song-link'));
		});
	});

app/views/artists/show.js.haml
:plain
	//var noAccounts = #{current_artist.youtube_token.nil? && current_artist.soundcloud_token.nil?};
	//console.log(noAccounts);
	//if(noAccounts) {
		//$('.modal#music-add').empty().html('#{j( render template: "users/add_media_account", formats: [:html] )}').show();
	//}
	//else {
	$('.modal#music-admin #artist-media .content').empty().html('#{j( render template: "artists/show", formats: [:html] )}');
	$('.modal#music-admin #artist-media .footer').empty().html('#{j( render "artists/music_admin_footer" )}')
	//}
	console.log('reloading...');
	

app/views/artists/show_artist_info.js.haml
:plain
	$('.callout#show-artist-profile').empty().html('#{j( render "artists/show_artist_profile", artist_id: @artist_id )}');
	

app/views/artists/unlink_media_account.js.haml
:plain
	accountId = '#{"#" + @account + "-unlink"}'
	console.log(accountId);
	$('#music-admin .reload-content .div-link').click();
	var messageFlash = #{@messages.to_json};
	if(messageFlash) {
		FlashManager.showMessage(messageFlash);
	}