config/routes.rb
SoundMelonV2Radio::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", passwords: "users/passwords", sessions: "users/sessions" }

  devise_scope :user do
    match '/signout', :to => 'devise/sessions#destroy', :as => :destroy_user_session

    #User routes
    match '/user/:id', to: 'users#show'
    match '/user_checkin', to: 'users#checkin'
    match '/email_signup', to: 'users#email_signup'
    match '/accept_terms', to: 'users#accept_terms'
    match '/init_fb_meta', to: 'users#init_fb_meta'
    match '/search_cities', to: 'users#search_cities'
    match '/add_city', to: 'users#add_city'
    match '/reload_fb_meta', to: 'users#reload_fb_meta'
    match '/update_user_meta', to: 'users#update_user_meta'
    match '/update_fb_meta', to: 'users#update_fb_meta'
    match '/add_favorite', to: 'users#add_favorite'
    match '/show_favorites', to: 'users#show_favorites'
    match '/update_favorites', to: 'users#update_favorites'
    match '/user_account', to: 'users#edit_account'
    match '/update_account', to: 'users#update_account'
    match '/add_media_account', to: 'users#add_media_account'
    match '/user_invites', to: 'users#new_invites'
    match '/user_remove', to: 'users#destroy'
  end

	resources :songs
  
  root to: 'welcome#index'

  match '/about', to: redirect('http://about.soundmelon.com')

#Admin routes
#	post 'send_mass_email' => 'users#send_mass_email'

#Report routes
	match '/report_song', to: 'reports#report_song'
	match '/send_report', to: 'reports#send_report'

#Feedback routes
	match '/feedback_form', to: 'feedbacks#new'
	match '/feedback_send', to: 'feedbacks#create'

#Artist routes
	match '/sc_request', to: 'artists#sc_request'
	match '/sc_oauth_callback', to: 'artists#sc_oauth_callback'
	match '/yt_request', to: 'artists#yt_request'
	match '/yt_oauth_callback', to: 'artists#yt_oauth_callback'
	match '/artist_show', to: 'artists#show'
	match '/artist_profile_update', to: 'artists#profile_update'
	match '/request_unlink', to: 'artists#request_unlink'
	match '/unlink_media_account', to: 'artists#unlink_media_account'
	match '/artist_profile_edit', to: 'artists#profile_edit'
	match '/artist_info', to: 'artists#show_artist_info'

#Song routes
	match '/make_public', to: 'songs#make_public'
	match '/request_playlist', to: 'songs#request_playlist'
  match '/request_history_reset', to: 'songs#history_reset'
	match '/get_source_tags', to: 'songs#get_source_tags'
	match '/new_song', to: 'songs#new'
	match '/edit_song', to: 'songs#edit'

	
#Invite routes
	match '/send_invite' => 'invites#create'
	match "/:invite_token", to: redirect('/')

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	#respond_to :js, :json, :html, :xml

	def index
		@invite_token = params[:invite_token]
	end

	# def about
	# 	# render 'welcome/about'
	# 	redirect_to '/about/index.html'
	# 	# render file: "/about/index.html"
	# end

	def register
	end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_email_signin.html.haml
= form_tag user_checkin_path, remote: true do
	= email_field_tag 'user[email]', nil, placeholder: "eMail"
	= password_field_tag 'user[password]', nil, placeholder: "password"
	.left.form-options
		= check_box_tag 'user[remember_me]'
		= label_tag 'user[remember_me]', 'Remember Me'
		.forgot-link.right= link_to "Forgot your password?", new_password_path(:user)
	.clear
	.right
		%input{type: 'submit', value: 'submit'}
	.clear
		
:javascript
	$("input, textarea").placeholder();

app/views/welcome/_email_signup.html.haml
= params.inspect
%h2 Sign up
= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
	= devise_error_messages!

	%div
		= f.label :first_name
		%br
		= f.text_field :first_name, autofocus: true

	%div
		= f.label :last_name
		%br
		= f.text_field :last_name

	%div
		= f.label :email
		%br
		= f.email_field :email

		%br
		/= f.email_field :confirm_email

	%div
		= f.label :password
		%br
		= f.password_field :password, autocomplete: "off"
		%div
		= f.label :password_confirmation
		%br
		= f.password_field :password_confirmation, autocomplete: "off"
	%div= f.submit "Sign up"

/= render "userssharedlinks"

app/views/welcome/_radio_page.html.haml
#user_page

	#radio-container
		- no_first_song = defined?(first_song).nil?
		#radio-view{'data-first-song' => no_first_song ? '' : first_song, 'data-first-song-played' => 'false'}
			= render "users/radio_player"

	:javascript
		
		$(document).ready(function() {
			initHomeFunctionality();
			$(".bg-wrapper").css('opacity', 1);
		});

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
      <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
      <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
        <link href="/stylesheets/site.css" media="screen" rel="stylesheet" type="text/css" />
        
      </meta>
      <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui' name='viewport'>
      <meta content='yes' name='apple-mobile-web-app-capable'>
    </meta>
    <title>About SoundMelon</title>
    <script src='javascripts/jquery-1.8.1.min.js' type='text/javascript'></script>
  </head>
  <body class='index'>
    <div id='main' role='main'>
      <header>
        <img src='images/logo.png'>
      </header>
      <div class='content scrollable'>
        <div class='framework'>
          <p>SoundMelon is a social media platform that empowers a community of artists and music lovers to connect and share the music they love and create.</p>
          <p>
            Our goals are far and wide, so to kick off this long journey we’ve launched
            <span>SoundMelon Radio,</span>
            the first piece of the puzzle. It’s so terribly simple to use, anyone with a melon could do it!
          </p>
          <p></p>
          <div class='indented'>
            <p>
              <span class='number'>1</span>
              Go to
              <a href='http://www.soundmelon.com'>www.soundmelon.com</a>
              and connect with your Facebook account. In connecting, we learn a little bit about what sort of music you like and what city you live in; it's how we connect you to music around you.
            </p>
            <p>
              <span class='number'>2</span>
              You’re now online with the radio! Hitting play will start playing out tunes that are tailored to your tastes from artists around you. You might hear a song by a band one morning and be able to watch a show of theirs that night!
            </p>
            <p>
              <span class='number'>3</span>
              If you’re an artist, just use the handy dandy add music link at the bottom to connect your SoundMelon account to SoundCloud or YouTube and within seconds your tunes are on the radio!
            </p>
          </div>
          <p>
            We have so many ideas in the hopper, this is only the beginning. Come on this ride with us, listen to some tunes, provide some feedback and let us know how you feel. Get meloning at
            <a href='http://www.soundmelon.com'>www.soundmelon.com.</a>
          </p>
        </div>
        <script>
          $(document).ready(function(){ 
            $('footer a').removeClass('framework-link-active team-link-active join-link-active hello-link-active');
            $('.framework-link').addClass('framework-link-active');
          });
        </script>
      </div>
      <footer>
        <div class='splat'></div>
        <div class='menu-container'>
          <div class='menu'>
                        <a class="framework-link" href="/"><i></i>
            the platform
            </a>

                        <a class="team-link" href="/team.html"><i></i>
            meet the team
            </a>

                        <a class="join-link" href="/join.html"><i></i>
            join us
            </a>

                        <a class="hello-link" href="/hello.html"><i></i>
            say hello
            </a>

          </div>
        </div>
        <div class='notes'>
          <div>
            <span>visit us</span>
                        <a href="http://www.facebook.com/soundmelon"><img src='images/footer_facebook.png'>
            </a>

                        <a href="http://www.twitter.com/soundmelon"><img src='images/footer_twitter.png'>
            </a>

                        <a href="http://www.linkedin.com/company/soundmelon?trk=tabs_biz_home"><img src='images/footer_linkedin.png'>
            </a>

          </div>
          <div class='contact'>
            <a href='mailto:hello@soundmelon.com'>hello@soundmelon.com</a>
          </div>
          <div>© 2014 SoundMelon Inc.</div>
        </div>
      </footer>
    </div>
  </body>
</html>
<script>
  $(document).bind("touchmove",function(e){
     e.preventDefault();
   });
  
  $('.scrollable').bind("touchmove",function(e){
    if ($('.scrollable')[0].scrollHeight > $('.scrollable')[0].clientHeight) {
      e.stopPropagation();
    } else {
      e.preventDefault();
    }
  });
  
  $('document').ready(function() {
    $(window).scrollTop(0);
  });
</script>

app/views/welcome/index.haml
%head
	%title= provide(:title, "SoundMelon")
	#welcome_page_div	
		.welcome_page
			%body
				%h2.center Welcome!
				.buttons
					%button#facebook 	CONNECT WITH FACEBOOK
					= link_to('REGISTER', signup_path, remote: true, class: 'page_link')
					= link_to('LOG IN', signin_path, remote: true, class: 'page_link')

		#lrn_div
			%p
				Lorem ipsum dolor sit amet, in salutandi assueverit vis, percipit deterruisset nec ad. Ne vim vero quodsi mollis, an summo interpretaris mea. Ei usu vero veri, sea nostrum appareat inimicus ne. His mucius petentium in, at vix recteque incorrupte.
			%br
			%p
				Nihil nostrud mei te. Ne vix omnesque sadipscing appellantur, appetere volutpat argumentum ea duo. Ea iisque accusamus deseruisse vel, pri no utroque efficiantur, at usu clita tollit saperet. Ius ea adhuc meliore, vel mazim referrentur neglegentur at. Ne melius placerat duo. Pri probo intellegam eu.
			%br
			= link_to('SO WHY NOT REGISTER?', signup_path, remote: true)

app/views/welcome/index.html.haml
/= current_or_guest_user.inspect
- if user_signed_in?
	= render template: 'users/show'
- else
	.inner-content.vertical-center.splash-page
		.bg-title.rotating-caption Find Your Tune

		.left.col-1-2.signin-section
			/= new_user_registration_url(locals: params)
			.signin-forms
				.email-signup
					.form-title login or signup
					= render 'welcome/email_signin'
				.buttons
					.form-title or you can
					#sign-in
						= link_to('CONNECT WITH FACEBOOK', user_omniauth_authorize_path(:facebook), remote: true)
						.caveat
							%span.strong recommended
							%span We use Facebook FOR basic social connectivity, learning about your likes and THE CITY YOU’re In. we respect your privacy.

		.right.col-1-2.intro-section
			.intro-blurb
				%p.emphasis
					%span SoundMelon is a radio tuned to you, and it’s 
					%span.strong completely free 
					%span to use.

				%p By signing up, we learn about your likes and the city you’re in and we create a station of local artists you might be in to. It’s also all we use Facebook for, and we respect your privacy.

				%p 
					%span If you’re an artist, you can add songs in seconds using 
					%span.strong SoundCloud 
					%span or 
					%span.strong YouTube.


				.about-button= link_to('Learn more about SoundMelon', "http://about.soundmelon.com", target: '_blank')

		.clear


:javascript
	var splashBGtween;

	inviteToken = '#{@invite_token}'
	console.log(inviteToken);


	
	var mozillaFlashMsg = '<div class="flash-msg">soundmelon needs flashplayer to run in firefox so please install it!</div>';
	var isFlash = navigator.mimeTypes ["application/x-shockwave-flash"] !== undefined ? 'flash' : 'no-flash';
	if(($.browser['mozilla']) && isFlash === 'no-flash') {
		$('.inner-content .buttons').html(mozillaFlashMsg);
	}

	if($('html').hasClass('mobile') && !$('html').hasClass('ipad')) {
		$(".inner-content").html('<div class="flash-msg">soundmelon is not yet supported on mobile devices!</div>')
	}

	$('.inner-content .buttons').show();

	$(document).ready(function() {

		$(".splash-bg").css({
			'background-image': 'url("#{asset_path('splash-bgs/' + rand(1..6).to_s + '.jpg')}")'
		});
	});