config/routes.rb
SoundMelonV2Radio::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", passwords: "users/passwords", sessions: "users/sessions" }

  devise_scope :user do
    match '/signout', :to => 'devise/sessions#destroy', :as => :destroy_user_session

    #User routes
    match '/user/:id', to: 'users#show'
    match '/user_checkin', to: 'users#checkin'
    match '/email_signup', to: 'users#email_signup'
    match '/accept_terms', to: 'users#accept_terms'
    match '/init_fb_meta', to: 'users#init_fb_meta'
    match '/search_cities', to: 'users#search_cities'
    match '/add_city', to: 'users#add_city'
    match '/reload_fb_meta', to: 'users#reload_fb_meta'
    match '/update_user_meta', to: 'users#update_user_meta'
    match '/update_fb_meta', to: 'users#update_fb_meta'
    match '/add_favorite', to: 'users#add_favorite'
    match '/show_favorites', to: 'users#show_favorites'
    match '/update_favorites', to: 'users#update_favorites'
    match '/user_account', to: 'users#edit_account'
    match '/update_account', to: 'users#update_account'
    match '/add_media_account', to: 'users#add_media_account'
    match '/user_invites', to: 'users#new_invites'
    match '/user_remove', to: 'users#destroy'
  end

	resources :songs
  
  root to: 'welcome#index'

  match '/about', to: redirect('http://about.soundmelon.com')

#Admin routes
#	post 'send_mass_email' => 'users#send_mass_email'

#Report routes
	match '/report_song', to: 'reports#report_song'
	match '/send_report', to: 'reports#send_report'

#Feedback routes
	match '/feedback_form', to: 'feedbacks#new'
	match '/feedback_send', to: 'feedbacks#create'

#Artist routes
	match '/sc_request', to: 'artists#sc_request'
	match '/sc_oauth_callback', to: 'artists#sc_oauth_callback'
	match '/yt_request', to: 'artists#yt_request'
	match '/yt_oauth_callback', to: 'artists#yt_oauth_callback'
	match '/artist_show', to: 'artists#show'
	match '/artist_profile_update', to: 'artists#profile_update'
	match '/request_unlink', to: 'artists#request_unlink'
	match '/unlink_media_account', to: 'artists#unlink_media_account'
	match '/artist_profile_edit', to: 'artists#profile_edit'
	match '/artist_info', to: 'artists#show_artist_info'

#Song routes
	match '/make_public', to: 'songs#make_public'
	match '/request_playlist', to: 'songs#request_playlist'
  match '/request_history_reset', to: 'songs#history_reset'
	match '/get_source_tags', to: 'songs#get_source_tags'
	match '/new_song', to: 'songs#new'
	match '/edit_song', to: 'songs#edit'

	
#Invite routes
	match '/send_invite' => 'invites#create'
	match "/:invite_token", to: redirect('/')

end

app/models/artist_upload.rb
class ArtistUpload < ActiveRecord::Base
  attr_accessible :song_id, :active, :upload_source, :song_url, :is_private, :sm_tags, :source_tags
	serialize :sm_tags
	serialize :source_tags
	belongs_to :artist
end

app/controllers/artist_uploads_controller.rb
class ArtistUploadsController < ApplicationController
	respond_to :js, :json, :html, :xml
	include ApplicationHelper

	def new
	end

	def create
		params[:artist_upload][:source_tags] = params[:artist_upload][:source_tags].split(',')
		params[:artist_upload][:sm_tags] = params[:artist_upload][:sm_tags].split(',')
		@items = params
		@artist_upload = ArtistUpload.create(params[:artist_upload].except(:artist_id))
		if @artist_upload.save
			@artist_upload.update_column(:artist_id, params[:artist_upload][:artist_id])
			flash[:upload_created] = true
		end
	end

	def edit
	end

	def update
		@artist_upload = ArtistUpload.find(params[:id])
		params[:artist_upload][:source_tags] = params[:artist_upload][:source_tags].split(',')
		params[:artist_upload][:sm_tags] = params[:artist_upload][:sm_tags].split(',')
		@artist_upload.update_attributes(params[:artist_upload])
		flash[:upload_updated] = true
	end

	def make_public
		@song_id = params[:song_id]
		@upload_source = params[:upload_source]
		@artist = Artist.find_by_id(params[:artist_id])
		if @upload_source == 'youtube'
			@client = new_yt_client(yt_auth_ids, @artist.youtube_token)
			@song = @client.my_video(@song_id)
			@client.video_update(@song_id, :title => @song.title, :description => @song.description, :category => @song.categories.first.term, :keywords => @song.source_tags, :private => false)
		elsif @upload_source == 'soundcloud'
			@client = refresh_sc_client(@artist)
			@song = @client.get('/tracks/' + @song_id)
			@client.put(@song.uri, :track => {:sharing => 'public'})
		end
	end

	def request_playlist
		@user = User.find_by_id(params[:user_id])
		@station = params[:station]
		if (@user.fb_meta.keys.size == 0 && @user.user_meta.size == 0)
			@station == 'random'
		end
		update_song_history(@user, params[:played_songs])
		@history = @user.song_history
		@active_songs = ArtistUpload.where(active: true)
		@playlist_size = 3
		@active_songs = filter_by_history(@user, @active_songs, @history, @playlist_size, @station)

		@active_ids = []
		@active_songs.each do |song|
			artist = Artist.find_by_id(song.artist_id)
			all_tags = song.sm_tags | song.source_tags
			@active_ids << {song_id: song.song_id, upload_source: song.upload_source, keywords: all_tags, song_url: song.song_url, artist_attrs: {artist_name: artist.artist_name, genre_tags: artist.genre_tags, website: artist.website, biography: artist.biography}, photo: artist.artist_photo.url(:thumb)}
		end

		respond_to do |format|
			format.json {render json: @active_ids}
		end
	end

	def get_source_tags
		@song_id = params[:song_id]
		@source = params[:source]
		@artist = Artist.find(params[:artist_id])
		if @source == 'youtube'
			@client = new_yt_client(yt_auth_ids, @artist.youtube_token)
			if @artist.youtube_token[:expires_at] < Time.now.to_i
				@client = refresh_yt_client(@client)
			end
			@source_tags = @client.my_video(@song_id).keywords
		elsif @source == 'soundcloud'
			@client = refresh_sc_client(@artist)
			@track = @client.get('/tracks/' + @song_id)
			@source_tags = @track.genre.split() | @track.tag_list.split(' ')
			@source_tags.delete_if {|tag| tag.include? "soundcloud:source"}
		end
		@source_tags = @source_tags.nil? ? [] : @source_tags
	end

end

app/views/artist_uploads/create.js.haml
:plain
	console.log('##{@artist_upload.song_id}');
	songDivId = '##{@artist_upload.song_id}';
	var newUpload = '#{flash[:upload_created].to_s}';
	if(newUpload === 'true') {
		$('#flash-board').hide().empty().html('Song Activated!').fadeIn().fadeOut();
	}
	console.log(newUpload);
	$(songDivId).append('<div class="edit-song"></div>');
	$(songDivId + ' .edit-song').html('#{escape_javascript( render template: "artist_uploads/edit" , locals: {song_id: @artist_upload.song_id, upload_source: @artist_upload.upload_source, song_url: @artist_upload.song_url, song_private: @artist_upload.is_private} )}').toggle();
	$(songDivId + ' .new-song').remove();

	var artistSong = $(songDivId);
	var songForm = artistSong.find('.song-form form');
	var activeToggle = artistSong.find('.ios-switch');
	var smTags =  artistSong.find('.sm-tags input');
	var sourceTags = artistSong.find('.source-tags input');

	activeToggle.click(function() {
		var state = $(this).prop('checked') ? 'active' : 'inactive';
		artistSong.find('.state').html(state);
		songForm.submit();
	});
	smTags.tagsInput({
		'removeWithBackspace': false,
		'defaultText': 'Add genres Eg. "ambient, fusion rap, rock \'n roll"',
		'height': 'auto',
		'width': 'auto',
		'onAddTag': function() {
			console.log(smTags.parent('form'));
			songForm.submit();
		},
		'onRemoveTag': function() {
			console.log(smTags.parent('form'));
			songForm.submit();
		}
	});

	sourceTags.tagsInput({
		'removeWithBackspace': false,
		'defaultText': '',
		'interactive': false,
		'height': 'auto',
		'width': 'auto',
		'onAddTag': function() {
			alert("You can not add source tags!");
		},
		'onRemoveTag': function() {
			console.log(sourceTags.parent('form'));
			songForm.submit();
		}
	});

app/views/artist_uploads/edit.html.haml
- @artist = current_artist
- @artist_upload = ArtistUpload.find_by_song_id(song_id)
- if song_private
	.private
		We can't stream private songs! Would you like to make this song public on #{upload_source}?
		= link_to "Make Public!", make_public_path(song_id: song_id, upload_source: upload_source, artist_id: @artist.id), remote: true, class: 'make-public', onclick: "$(this).siblings('.spinner').show()"
		.spinner

.song-form

	= form_for(@artist_upload, remote: true) do |f|
		= render 'artist_uploads/upload_form', {f: f, active: @artist_upload.active, sm_tags: @artist_upload.sm_tags, source_tags: @artist_upload.source_tags, song_id: song_id, source: upload_source}

app/views/artist_uploads/new.html.haml
- @artist = current_artist
- if song_private
	.private
		We can't stream private songs! Would you like to make this song public on #{upload_source}?
		= link_to "Make Public!", make_public_path(song_id: song_id, upload_source: upload_source, artist_id: @artist.id), remote: true, class: 'make-public', onclick: "$(this).siblings('.spinner').show()"
		.spinner

.song-form
	- @artist_upload = ArtistUpload.new
	= form_for(@artist_upload, remote: true) do |f|
		= render 'artist_uploads/upload_form', {f: f, active: @artist_upload.active, source_tags: source_tags, song_id: song_id, source: upload_source}
		= f.hidden_field :artist_id, value: @artist.id
		= f.hidden_field :song_id, value: song_id
		= f.hidden_field :upload_source, value: upload_source
		= f.hidden_field :song_url, value: song_url